# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  user: root
  database: annoyr_development
  pool: 5
  timeout: 5

test:
  adapter: mysql2
  user: root
  database: annoyr_test
  pool: 5
  timeout: 5

production:
  adapter: mysql2
  user: root
  database: annoyr_production
  pool: 5
  timeout: 5
